### ISSUE TITLE
End Game

### ISSUE THREAD

**Issue by amandou** [amandou/Shoot-em-up-Game#11]
# Expected Behavior
The game must and when the player's heath is bellow 1 or  when the session time is eneded

# Tasks
- [x] Create End game screen
- This screen must show the player total points and two choices: “Play Again” and “Main Menu”.
- [x] Implement Timer count down.
- [x] Get game session reference from options menu.
- [x] Avoid enemys spawn after the player is dead.

# Additional Information

# Screenshots
